package com.byhealth.xuan.wen.qin.cxf.server.ws;

import javax.jws.WebParam;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.7 2016-09-09T13:55:11.436+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService
public interface UserService {

	public com.byhealth.xuan.wen.qin.cxf.server.ws.UserModel findById(@WebParam(name = "id")long id);

	public boolean delete(@WebParam(name = "id")long id);

	public java.util.List<com.byhealth.xuan.wen.qin.cxf.server.ws.UserModel> findAll();

	public java.lang.String singin(@WebParam(name = "userName")java.lang.String userName, @WebParam(name = "password")java.lang.String password);

	public long add(@WebParam(name = "model")com.byhealth.xuan.wen.qin.cxf.server.ws.UserModel model);
}
